### PR TITLE
Port to dune

### PR DESCRIPTION
**Pull request by imbsky**

### CODE REVIEW

**Comment by imbsky** [comment]
This PR will delete the Makefile and replace it with Dune. Dune provides many additional benefits, including automatic formatting with ocamlformat. By the way, Dune 2.0 has been released, but in 2.0 the automatic generation of opam files is broken, so there is still no advantage to using it on such small projects.

**Comment by imbsky** [comment]
This should also make it easier to use this library with Guedra and others. (You can use this library without exposing it to the opam repository using the `opam pin`.) If you want, I will make similar changes to Guedra after this PR is merged.

**Comment by hatsugai** [comment]
Thank you for the PR. I am not familiar with Dune but I will examine it later.

**Comment by imbsky** [comment]
Using opam and dune ensures that libraries can be built and used anywhere. They are really useful and I would definitely recommend checking them out 🙂

**Comment by imbsky** [comment]
The automatic generation of opam files bug was fixed yesterday. It should probably be in the next (2.4.0) release!

**Pull request merged**
